package gui;

import clases.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Olman
 */
public class VAdopciones extends javax.swing.JFrame {
    private ImageIcon imagen;
    private Icon icono;
    
    public VTipoAnimal tipo;
    DefaultTableModel listTipo = new DefaultTableModel();

    public int idAnimal;
    public String descripcion; 
    public int indice;
    
    public VAdopciones() {
        initComponents();
        this.setTitle("Registrar Adopciones"); //Título de la ventana de la GUI.
        this.setLocationRelativeTo(null); //Centrar la ventana de la GUI.
        this.ajustarImagen(this.label_Imagen1, "src\\com\\images\\pet.png");
        
        listTipo = (DefaultTableModel)this.jTablaListaTipo.getModel();
        cargarStackTipos();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_DNI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Costo = new javax.swing.JTextField();
        check_CertificacionRaza = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_GuardarAdopcion = new javax.swing.JButton();
        btn_GenerarDNI = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Domicilio = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablaListaTipo = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btn_Cerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label_Imagen1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(801, 556));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("DNI:");

        txt_DNI.setEditable(false);
        txt_DNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DNIKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        txt_Costo.setEnabled(false);
        txt_Costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CostoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CostoKeyTyped(evt);
            }
        });

        check_CertificacionRaza.setText("Tiene certificación de raza ");
        check_CertificacionRaza.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Domicilio de la persona que adopta:");

        txt_Nombre.setEnabled(false);
        txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Costo:");

        btn_GuardarAdopcion.setBackground(new java.awt.Color(255, 255, 0));
        btn_GuardarAdopcion.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btn_GuardarAdopcion.setText("Guardar adopción");
        btn_GuardarAdopcion.setEnabled(false);
        btn_GuardarAdopcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarAdopcionActionPerformed(evt);
            }
        });

        btn_GenerarDNI.setBackground(new java.awt.Color(102, 102, 255));
        btn_GenerarDNI.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btn_GenerarDNI.setText("Generar DNI");
        btn_GenerarDNI.setEnabled(false);
        btn_GenerarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerarDNIActionPerformed(evt);
            }
        });

        txt_Domicilio.setColumns(20);
        txt_Domicilio.setRows(5);
        txt_Domicilio.setEnabled(false);
        txt_Domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DomicilioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DomicilioKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txt_Domicilio);

        jTablaListaTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID tipo Animal", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaListaTipo.setRowHeight(20);
        jTablaListaTipo.getTableHeader().setReorderingAllowed(false);
        jTablaListaTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaListaTipoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablaListaTipo);
        if (jTablaListaTipo.getColumnModel().getColumnCount() > 0) {
            jTablaListaTipo.getColumnModel().getColumn(0).setResizable(false);
            jTablaListaTipo.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Tipo de animales:");

        btn_Cerrar.setBackground(new java.awt.Color(51, 255, 51));
        btn_Cerrar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btn_Cerrar.setText("Volver");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 102));

        jLabel7.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel7.setText("Registra la adopción");
        jLabel7.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel9.setText("Animales");
        jLabel9.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(label_Imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
            .addComponent(label_Imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel11.setText("#Haga click en algun tipo de animal a escoger");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_GuardarAdopcion))
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(check_CertificacionRaza))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(76, 76, 76)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_GenerarDNI))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_GenerarDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_CertificacionRaza)
                    .addComponent(txt_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_GuardarAdopcion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DNIKeyReleased
        habilitarbtnGuardar();
    }//GEN-LAST:event_txt_DNIKeyReleased

    private void txt_CostoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CostoKeyReleased
        habilitarbtnGuardar();
    }//GEN-LAST:event_txt_CostoKeyReleased

    private void txt_CostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CostoKeyTyped

        char caracter = evt.getKeyChar();

        if(((caracter < '0' || caracter > '9'))
            && (caracter != KeyEvent.VK_BACK_SPACE)
            && ((caracter != '.') || txt_Costo.getText().contains("."))) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

    }//GEN-LAST:event_txt_CostoKeyTyped

    private void txt_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyReleased
        habilitarbtnGuardar();
    }//GEN-LAST:event_txt_NombreKeyReleased

    private void txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyTyped
        //Condicional de la dirección para no exceder más caracteres
        if (txt_Nombre.getText().length() > 20) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txt_NombreKeyTyped

    private void btn_GuardarAdopcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarAdopcionActionPerformed
        double costoAux; //Auxiliar de costo para asignarle dos decimales
        Adopciones adoptar = new Adopciones(); //Instancia de nuevo adoptar

        //Recoger los datos de adoptar
        adoptar.setIdTipoAnimal(idAnimal);
        adoptar.setDescripcion(descripcion);

        adoptar.setDni(this.txt_DNI.getText());
        adoptar.setNombre(this.txt_Nombre.getText());

        if(check_CertificacionRaza.isSelected()){
            adoptar.setCertificacionRaza(true);
        }else{
            adoptar.setCertificacionRaza(false);
        }

        adoptar.setDomicilio(this.txt_Domicilio.getText());

        //Metodo para asignar dos decimales maximo al numero digitado
        DecimalFormat df = new DecimalFormat("#.00");
        costoAux = Double.valueOf(this.txt_Costo.getText());

        adoptar.setCosto(Double.valueOf(df.format(costoAux))); //Pasar el dato al objeto costo

        //Recorrer el stack con un iterator para asignar las colas independientes
        VTipoAnimal tipo = new VTipoAnimal();
        for (Iterator<TipoAnimales> iterator = tipo.tipoStack.iterator(); iterator.hasNext();) {
            TipoAnimales next = iterator.next();

            //Condicional para guardar los datos de adoptar a su respectiva ID en las colas por ID tipo animal
            if(next.getIdTipoAnimal() == idAnimal){

                next.getAdopcionesQueue().offer(adoptar);

            }

        }
        refrescarTablaTipo();
        cargarStackTipos();
        reset();
    }//GEN-LAST:event_btn_GuardarAdopcionActionPerformed

    private void btn_GenerarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerarDNIActionPerformed
        //Codigo UUID a generar para el DNI
        UUID uuid = UUID.randomUUID();
        txt_DNI.setText(uuid.toString());

        habilitarbtnGuardar();
    }//GEN-LAST:event_btn_GenerarDNIActionPerformed

    private void txt_DomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DomicilioKeyReleased
        habilitarbtnGuardar();
    }//GEN-LAST:event_txt_DomicilioKeyReleased

    private void txt_DomicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DomicilioKeyTyped

        //Condicional de la dirección para no exceder más caracteres
        if (txt_Domicilio.getText().length() > 200) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txt_DomicilioKeyTyped

    private void jTablaListaTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaListaTipoMouseClicked
        //Pasar un auxiliar el indice de la tabla seleccionada
        indice = jTablaListaTipo.rowAtPoint(evt.getPoint());
        //Auxiliar de ID animal y descripción segun el indice clickeado
        idAnimal = Integer.parseInt(listTipo.getValueAt(indice, 0).toString());
        descripcion = listTipo.getValueAt(indice, 1).toString();

        //Habilitar botones de la pantalla adopción si se marca un tipo
        if(indice >= 0){
            btn_GenerarDNI.setEnabled(true);
            txt_Nombre.setEnabled(true);
            txt_Costo.setEnabled(true);
            txt_Domicilio.setEnabled(true);
            check_CertificacionRaza.setEnabled(true);

        }

    }//GEN-LAST:event_jTablaListaTipoMouseClicked

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
       MenuPrincipal menu = new MenuPrincipal();
       menu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    public void habilitarbtnGuardar(){
         
         if(!txt_DNI.getText().isEmpty() && !txt_Nombre.getText().isEmpty() 
         && !txt_Costo.getText().isEmpty() && !txt_Domicilio.getText().isEmpty()){
             btn_GuardarAdopcion.setEnabled(true);          
         }else{
             btn_GuardarAdopcion.setEnabled(false);
         }
    
     }
    
    public void refrescarTablaTipo(){
        int fila;
        //Borrar datos de tablas tipo
        fila = listTipo.getRowCount();

        for(int i = fila-1;i >=0; i--){  
         listTipo.removeRow(i);
         
        } 
    }
    
    private void cargarStackTipos(){
         //Recorrer el stack para llenar las tablas tipoAnimal
         for (Iterator<TipoAnimales> iterator = tipo.tipoStack.iterator(); iterator.hasNext();) {
            TipoAnimales next = iterator.next();
            
            listTipo.addRow(new Object[]{

                next.getIdTipoAnimal(), next.getDescripcion()

            });
         }
     }
    
    public void reset(){
        this.txt_DNI.setText("");
        this.txt_Costo.setText("");
        this.txt_Domicilio.setText("");
        this.txt_Nombre.setText("");
        this.check_CertificacionRaza.setSelected(false);
        this.check_CertificacionRaza.setEnabled(false);
        btn_GenerarDNI.setEnabled(false);
        btn_GuardarAdopcion.setEnabled(false);
        
    }
    
    private void ajustarImagen(JLabel lbl, String ruta){
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(
                lbl.getWidth(), 
                lbl.getHeight(), 
                Image.SCALE_DEFAULT
             )   
      );
      lbl.setIcon(this.icono);
      this.repaint();      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdopciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdopciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_GenerarDNI;
    private javax.swing.JButton btn_GuardarAdopcion;
    private javax.swing.JCheckBox check_CertificacionRaza;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablaListaTipo;
    private javax.swing.JLabel label_Imagen1;
    private javax.swing.JTextField txt_Costo;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextArea txt_Domicilio;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
